[package]
name = "wpust"
version = "0.1.0"
edition = "2024"

[dependencies]
open = "5"
crossterm = "0.29.0"
ratatui = { version = "0.29.0", features = ["all-widgets"] }
color-eyre = "0.6"
clap = { version = "4.5.51", features = ["derive"] }
dns-lookup = "3.0.1"
url = "2.5"
hickory-resolver = "0.24"
